# Actualizado a Python 3.12 según requerimiento
FROM python:3.12-slim

# 1. Permite ver los logs en tiempo real en Cloud Run (Vital para debug)
ENV PYTHONUNBUFFERED=True

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 2. Cloud Run inyecta la variable PORT=8080 por defecto.
ENV PORT=8080

# 3. Usamos 'exec' para que las señales de apagado lleguen bien a Gunicorn
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app