"""Agregar campo id_local a Usuario

Revision ID: 0a6d2bd87fb9
Revises: f7e8fcdc9a00
Create Date: 2025-11-29 20:46:59.275551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6d2bd87fb9'
down_revision: Union[str, Sequence[str], None] = 'f7e8fcdc9a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_local', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usuario_id_local'), 'usuario', ['id_local'], unique=False)
    op.create_foreign_key(None, 'usuario', 'local', ['id_local'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_index(op.f('ix_usuario_id_local'), table_name='usuario')
    op.drop_column('usuario', 'id_local')
    # ### end Alembic commands ###
