"""Agregar campo descripcion a tabla local

Revision ID: 999eb7469dea
Revises: e4275ec7890a
Create Date: 2025-11-24 23:18:32.563365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999eb7469dea'
down_revision: Union[str, Sequence[str], None] = 'e4275ec7890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local', sa.Column('descripcion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local', 'descripcion')
    # ### end Alembic commands ###
