"""Agregar campo calle a tabla direccion

Revision ID: e4275ec7890a
Revises: 451d73b4102a
Create Date: 2025-11-24 23:15:44.474973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4275ec7890a'
down_revision: Union[str, Sequence[str], None] = '451d73b4102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna como nullable primero
    op.add_column('direccion', sa.Column('calle', sa.String(length=200), nullable=True))
    
    # Actualizar registros existentes con valor por defecto
    op.execute("UPDATE direccion SET calle = 'Sin especificar' WHERE calle IS NULL")
    
    # Ahora hacer la columna NOT NULL
    op.alter_column('direccion', 'calle', nullable=False)
    
    op.drop_index(op.f('ix_pago_reserva_id'), table_name='pago')
    op.drop_constraint(op.f('pago_reserva_id_fkey'), 'pago', type_='foreignkey')
    op.drop_column('pago', 'reserva_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('reserva_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pago_reserva_id_fkey'), 'pago', 'reserva', ['reserva_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_pago_reserva_id'), 'pago', ['reserva_id'], unique=False)
    op.drop_column('direccion', 'calle')
    # ### end Alembic commands ###
